.Dd November 21, 2022
.Dt CCHRISTMAS 1
.Sh NAME
.Nm cchristmas
.Nd christmas tree in the terminal
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh DESCRIPTION
The
.Nm
application displays a simple christmas tree inside the terminal.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/cchristmas/issues
